import '@styles/globals.css'

import Nav from '@components/Nav'
import Provider from '@components/Provider'

export const metadata = {
    title: 'Prompts Web',
    description: 'Generated by create next app',
}
const RootLayout = ({ children }) => {
    return (
        <html lang='en'>
            <head>
            <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css"/>
                <link
                    rel="stylesheet"
                    type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
                />
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
            </head>
            <body>
                <Provider >
                    <div className='main'>
                        <div className='gradient'></div>
                    </div>
                    <main className='app'><Nav />{children}</main>
                </Provider>
            </body>
        </html>
    )
}

export default RootLayout
